TGH5.settings = {
	"platformsConfig": {
		"configFiles": {
			"default": "settings_comcast.js",
			"lg": "settings_lg.js",
			"webos": "settings_webos.js",
			"samsung": "settings_samsung.js",
			"vizio": "settings_vizio.js",
			"vizio_via": "settings_vizio_via.js",
			"dishtv" : "settings_dishtv.js",
			"philips" : "settings_philips.js",
			"zeasn": "settings_zeasn.js",
			"vewd": "settings_vewd.js",
			"vidaa": "settings_vidaa.js",
			"youview": "settings_youview.js",
			"bt": "settings_bt.js",
			"retail": "settings_retail.js",
			"talktalk": "settings_talktalk.js",
			"sony_youview": "settings_sony_youview.js",
			"lgi": "settings_lgi.js",
			"lightning": "settings_lightning.js",
			"orange": "settings_orange.js",
			"verizon": "settings_verizon.js",
			"comcast_reg": "settings_comcast_reg.js",
			"comcast_kids": "settings_comcast_kids.js",
			"tellytv": "settings_tellytv.js",
			"cogeco": "settings_cogeco.js",
			"webos_motor": "settings_webos_motor.js",
			"sony": "settings_sony.js",
			"netgem": "settings_netgem.js",
			"sling_androidtv" : "settings_sling_androidtv.js",
			"sling_firetv": "settings_sling_firetv.js",
			"sling_samsung": "settings_sling_samsung.js",
			"sling_lg": "settings_sling_lg.js",
			"sling_vizio": "settings_sling_vizio.js",
			"sling_comcast": "settings_sling_comcast.js",
			"sling_airtvplayer": "settings_sling_airtvplayer.js",
			"sling_kepler": "settings_sling_kepler.js",
			"hilton": "settings_hilton.js",
			"deutch_telecom": "settings_deutch_telecom.js",
			"virgin": "settings_virgin.js",
			"titan": "settings_titan.js",
			
			//gameloop
			"gameloop_lg": "settings_gameloop_lg.js",
			"gameloop_adth": "settings_gameloop_adth.js",
			"gameloop_sony": "settings_gameloop_sony.js",
			"gameloop_hisense": "settings_gameloop_hisense.js",
			"gameloop_samsung": "settings_gameloop_samsung.js",
			"gameloop_samsung_ctv": "settings_gameloop_samsung.js",
			"gameloop_zinwell": "settings_gameloop_zinwell.js",
			
			"mobitech": "settings_mobitech.js",
			"mobitech_lenovo": "settings_mobitech_lenovo.js",
			"mobitech_tcl": "settings_mobitech_tcl.js",
			"mobitech_xiaomi": "settings_mobitech_xiaomi.js",
			"mobitech_coolita": "settings_mobitech_coolita.js",
			
			"fetch": "settings_fetch.js",
			"android_hilton": "settings_hilton_android.js",
			
			// for AVODs
			"comcast": "settings_comcast.js",
			"videotron": "settings_videotron.js",
			"cox": "settings_cox.js",
			"firetv": "settings_firetv.js",
			"sky": "settings_sky.js",
			"sky_uk": "settings_sky_uk.js",
			"sky_uk_glass": "settings_sky_uk_glass.js",
			"sky_de": "settings_sky_de.js",
			"sky_it": "settings_sky_it.js",
			"cordova": "settings_cordova.js",
			"shaw": "settings_shaw.js",
			"html": "settings_html.js",
			"rogers": "settings_rogers.js",
			"review": "settings_review.js",
			"metrological": "settings_metrological.js"
		}
	}
}